#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color '#458588'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
wireplumber &
pipewire &
pipewire-pulse &
polybar &
redshift &
feh --bg-fill ~/Pictures/Wallpapers/canyon.jpg &
setxkbmap -layout us,ara -option 'grp:alt_shift_toggle'

