;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282828 
primary = #D79921
secondary = #CC241D
alert = #A54242
disabled = #707880
foreground = #FBF1C7

[bar/example]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = 
separator-foreground = ${colors.disabled}

font-0 = GohuFont uni14 Nerd Font :size=10;1
font-2 = Emoji:size=10;1

modules-left = brand xworkspaces xwindow
modules-right = xkeyboard pulseaudio memory cpu battery wlan powermenu
modules-center = date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/brand]
type = custom/text
content =   tetris  
content-padding = 1

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.secondary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = "  "
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}


[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.secondary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.secondary}
label = %percentage:2%%

[module/battery]
type = internal/battery

battery = BAT1
adapter = ACAD

full-at = 99

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 󰂄 %percentage%%

ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁼
ramp-capacity-2 = 󰁿
ramp-capacity-3 = 󰂁
ramp-capacity-4 = 󰁹

animation-charging-0 = 󰢟
animation-charging-1 = 󰂇
animation-charging-2 = 󰂉
animation-charging-3 = 󰂊
animation-charging-4 = 󰂅
animation-charging-framerate = 750


[network-base]
type = internal/network
interval = 3.0
format-connected = 󰖩 
format-disconnected = 󰖪 
label-disconnected = disconnected


[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid%

[module/date]
type = internal/date
interval = 1

time = %A, %d %b %Y, %H:%M

label = %time%
label-foreground = ${colors.primary}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${colors.alert}
label-close =  cancel
label-close-foreground = ${colors.alert}
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = reboot

menu-2-0 = power off
menu-2-0-exec = poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0


[settings]
screenchange-reload = true
pseudo-transparency = true


; vim:ft=dosini
