[ImageGrabber]
LastRectArea=@Rect(64 163 1801 830)

[MainWindow]
Position=@Point(20 52)

[recentImagesPath]
1\imagePath=/home/tetris/ksnip_20260320-124105.png
2\imagePath=/home/tetris/ksnip_20260324-080313.png
size=2
